/*
 * This file is part of ViaProxyAuthHook - https://github.com/ViaVersionAddons/ViaProxyAuthHook
 * Copyright (C) 2024-2025 RK_01/RaphiMC and contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package net.lenni0451.authhook;

import java.lang.instrument.Instrumentation;
import java.util.Map;

public class Agent {

    public static void agentmain(final String args, final Instrumentation instrumentation) {
        hook(instrumentation);
    }

    public static void premain(final String args, final Instrumentation instrumentation) {
        hook(instrumentation);
    }

    private static void hook(final Instrumentation instrumentation) {
        try {
            Map<String, String> config = Config.load();
            if (config.get(Config.SECRET_KEY).contains(" ")) {
                System.err.println("Please set a valid secret key in the auth_hook.properties file");
                System.err.println("It is automatically generated by ViaProxy if you have the AuthHook plugin installed");
                System.exit(-1);
            }

            instrumentation.addTransformer(new URLRedirector(config), true);
        } catch (Throwable t) {
            System.err.println("An error occurred while starting AuthHook");
            t.printStackTrace();
            System.exit(-1);
        }
    }

}
